const players = [
  {
    "_id": "602c53dac004f7608c294f51",
    "name": "Sedtawat Padsawud",
    "firstName": "Sedtawat",
    "lastName": "Padsawud",
    "gender": "M",
    "nationality": "Thailand",
    "playerId": "13843",
    "tournaments": [
      {
        "_id": "602c53dac004f7608c294f52",
        "tournamentName": "Bandar Torkaman",
        "tournamentCountry": "Iran",
        "tournamentId": "3735",
        "season": 2020,
        "finish": 1,
        "seed": "3",
        "partnerName": "Nuttanon Inkiew",
        "partnerFirstName": "Nuttanon",
        "partnerLastName": "Inkiew",
        "partnerBVId": "17546"
      },
      {
        "_id": "602c53f3c004f7608c29555e",
        "tournamentName": "Qinzhou",
        "tournamentCountry": "China",
        "tournamentId": "3731",
        "season": 2020,
        "finish": 25,
        "seed": "25, Q2",
        "partnerName": "Nuttanon Inkiew",
        "partnerFirstName": "Nuttanon",
        "partnerLastName": "Inkiew",
        "partnerBVId": "17546"
      },
      {
        "_id": "602c541eb69be7d2d842ea22",
        "tournamentName": "Qinzhou",
        "tournamentCountry": "China",
        "tournamentId": "3535",
        "season": 2019,
        "finish": 9,
        "seed": "11",
        "partnerName": "Nuttanon Inkiew",
        "partnerFirstName": "Nuttanon",
        "partnerLastName": "Inkiew",
        "partnerBVId": "17546"
      },
      {
        "_id": "602c5423b69be7d2d842eb06",
        "tournamentName": "Yangzhou",
        "tournamentCountry": "China",
        "tournamentId": "3447",
        "season": 2019,
        "finish": 17,
        "seed": "22, Q2",
        "partnerName": "Nuttanon Inkiew",
        "partnerFirstName": "Nuttanon",
        "partnerLastName": "Inkiew",
        "partnerBVId": "17546"
      },
      {
        "_id": "602c5432b69be7d2d842eddd",
        "tournamentName": "The Hague",
        "tournamentCountry": "Netherlands",
        "tournamentId": "3572",
        "season": 2019,
        "finish": 25,
        "seed": "20",
        "partnerName": "Nuttanon Inkiew",
        "partnerFirstName": "Nuttanon",
        "partnerLastName": "Inkiew",
        "partnerBVId": "17546"
      },
      {
        "_id": "602c543bb69be7d2d842efa8",
        "tournamentName": "Sydney",
        "tournamentCountry": "Australia",
        "tournamentId": "3634",
        "season": 2019,
        "finish": 25,
        "seed": "22",
        "partnerName": "Surin Jongklang",
        "partnerFirstName": "Surin",
        "partnerLastName": "Jongklang",
        "partnerBVId": "15651"
      },
      {
        "_id": "602c544fb69be7d2d842f36b",
        "tournamentName": "Xiamen",
        "tournamentCountry": "China",
        "tournamentId": "3591",
        "season": 2019,
        "finish": 41,
        "seed": "Q14",
        "partnerName": "Nuttanon Inkiew",
        "partnerFirstName": "Nuttanon",
        "partnerLastName": "Inkiew",
        "partnerBVId": "17546"
      },
      {
        "_id": "602c5455b69be7d2d842f4ac",
        "tournamentName": "Kuala Lumpur",
        "tournamentCountry": "Malaysia",
        "tournamentId": "3595",
        "season": 2019,
        "finish": 25,
        "seed": "21",
        "partnerName": "Nuttanon Inkiew",
        "partnerFirstName": "Nuttanon",
        "partnerLastName": "Inkiew",
        "partnerBVId": "17546"
      },
      {
        "_id": "602c5460b69be7d2d842f683",
        "tournamentName": "Jinjiang",
        "tournamentCountry": "China",
        "tournamentId": "3642",
        "season": 2019,
        "finish": 33,
        "seed": "Q5",
        "partnerName": "Nuttanon Inkiew",
        "partnerFirstName": "Nuttanon",
        "partnerLastName": "Inkiew",
        "partnerBVId": "17546"
      },
      {
        "_id": "602c5473b69be7d2d842f9dd",
        "tournamentName": "Warsaw",
        "tournamentCountry": "Poland",
        "tournamentId": "3609",
        "season": 2019,
        "finish": 41,
        "seed": "Q22",
        "partnerName": "Banlue Nakprakhong",
        "partnerFirstName": "Banlue",
        "partnerLastName": "Nakprakhong",
        "partnerBVId": "15652"
      },
      {
        "_id": "602c547eb69be7d2d842fbe6",
        "tournamentName": "Qidong",
        "tournamentCountry": "China",
        "tournamentId": "3615",
        "season": 2019,
        "finish": 19,
        "seed": "15",
        "partnerName": "Nuttanon Inkiew",
        "partnerFirstName": "Nuttanon",
        "partnerLastName": "Inkiew",
        "partnerBVId": "17546"
      },
      {
        "_id": "602c548db69be7d2d842fecb",
        "tournamentName": "Edmonton",
        "tournamentCountry": "Canada",
        "tournamentId": "3622",
        "season": 2019,
        "finish": 33,
        "seed": "Q6",
        "partnerName": "Nuttanon Inkiew",
        "partnerFirstName": "Nuttanon",
        "partnerLastName": "Inkiew",
        "partnerBVId": "17546"
      },
      {
        "_id": "602c5491b69be7d2d842ff70",
        "tournamentName": "Tokyo",
        "tournamentCountry": "Japan",
        "tournamentId": "3625",
        "season": 2019,
        "finish": 25,
        "seed": "Q17",
        "partnerName": "Nuttanon Inkiew",
        "partnerFirstName": "Nuttanon",
        "partnerLastName": "Inkiew",
        "partnerBVId": "17546"
      },
      {
        "_id": "602c54b3b69be7d2d84304b8",
        "tournamentName": "Jurmala",
        "tournamentCountry": "Latvia",
        "tournamentId": "3730",
        "season": 2019,
        "finish": 25,
        "seed": "23, Q1",
        "partnerName": "Nuttanon Inkiew",
        "partnerFirstName": "Nuttanon",
        "partnerLastName": "Inkiew",
        "partnerBVId": "17546"
      },
      {
        "_id": "602c54b6b69be7d2d843051f",
        "tournamentName": "Montpellier",
        "tournamentCountry": "France",
        "tournamentId": "3726",
        "season": 2019,
        "finish": 5,
        "seed": "3",
        "partnerName": "Nuttanon Inkiew",
        "partnerFirstName": "Nuttanon",
        "partnerLastName": "Inkiew",
        "partnerBVId": "17546"
      }
    ],
    "matches": [
      {
        "opponents": {
          "opponentA": "Sina Enayati",
          "opponentAId": "17410",
          "opponentB": "Amir Shoushtarizadeh",
          "opponentBId": "16550",
          "opponentNationality": "Iran",
          "opponentNationalityCode": ""
        },
        "_id": "602c5639a7bbbbac8807b95d",
        "tournament": "Bandar Torkaman",
        "tournamentId": "3735",
        "season": 2020,
        "round": "Pool Play 1st Round",
        "partner": "Nuttanon Inkiew",
        "partnerId": "17546",
        "result": "Win",
        "score": "21-13, 21-17",
        "matchLength": "0:29"
      },
      {
        "opponents": {
          "opponentA": "Kitti Duangjinda",
          "opponentAId": "18105",
          "opponentB": "Dunwinit Kaewsai",
          "opponentBId": "18166",
          "opponentNationality": "Thailand",
          "opponentNationalityCode": ""
        },
        "_id": "602c5639a7bbbbac8807b965",
        "tournament": "Bandar Torkaman",
        "tournamentId": "3735",
        "season": 2020,
        "round": "Pool Play 2nd Round",
        "partner": "Nuttanon Inkiew",
        "partnerId": "17546",
        "result": "Win",
        "score": "21-17, 21-16",
        "matchLength": "0:33"
      },
      {
        "opponents": {
          "opponentA": "Peiman Dargahi",
          "opponentAId": "18124",
          "opponentB": "Vahid Nikoufar",
          "opponentBId": "16557",
          "opponentNationality": "Iran",
          "opponentNationalityCode": ""
        },
        "_id": "602c5639a7bbbbac8807b995",
        "tournament": "Bandar Torkaman",
        "tournamentId": "3735",
        "season": 2020,
        "round": " 5th Place Match",
        "partner": "Nuttanon Inkiew",
        "partnerId": "17546",
        "result": "Win",
        "score": "11-21, 21-18, 15-13",
        "matchLength": "0:43"
      },
      {
        "opponents": {
          "opponentA": "Hitoshi Murakami",
          "opponentAId": "10957",
          "opponentB": "Takashi Tsuchiya",
          "opponentBId": "17403",
          "opponentNationality": "Japan",
          "opponentNationalityCode": ""
        },
        "_id": "602c5639a7bbbbac8807b9a1",
        "tournament": "Bandar Torkaman",
        "tournamentId": "3735",
        "season": 2020,
        "round": "Semifinals ",
        "partner": "Nuttanon Inkiew",
        "partnerId": "17546",
        "result": "Win",
        "score": "21-17, 21-19",
        "matchLength": "0:39"
      },
      {
        "opponents": {
          "opponentA": "Alireza Aghajani",
          "opponentAId": "16934",
          "opponentB": "Javad Firouzpourbandpei",
          "opponentBId": "17338",
          "opponentNationality": "Iran",
          "opponentNationalityCode": ""
        },
        "_id": "602c5639a7bbbbac8807b9a9",
        "tournament": "Bandar Torkaman",
        "tournamentId": "3735",
        "season": 2020,
        "round": "Gold Medal Match ",
        "partner": "Nuttanon Inkiew",
        "partnerId": "17546",
        "result": "Win",
        "score": "17-21, 21-17, 14-12 retired",
        "matchLength": "0:55"
      },
      {
        "opponents": {
          "opponentA": "Kitti Duangjinda",
          "opponentAId": "18105",
          "opponentB": "Dunwinit Kaewsai",
          "opponentBId": "18166",
          "opponentNationality": "Thailand",
          "opponentNationalityCode": ""
        },
        "_id": "602c563ba7bbbbac8807c37d",
        "tournament": "Qinzhou",
        "tournamentId": "3731",
        "season": 2020,
        "round": "Qualification 2nd Round",
        "partner": "Nuttanon Inkiew",
        "partnerId": "17546",
        "result": "Win",
        "score": "27-25, 21-15",
        "matchLength": "0:34"
      },
      {
        "opponents": {
          "opponentA": "Peng Gao",
          "opponentAId": "8081",
          "opponentB": "Yang Li",
          "opponentBId": "10185",
          "opponentNationality": "China",
          "opponentNationalityCode": ""
        },
        "_id": "602c563ba7bbbbac8807c3f3",
        "tournament": "Qinzhou",
        "tournamentId": "3731",
        "season": 2020,
        "round": "Pool Play 1st Round",
        "partner": "Nuttanon Inkiew",
        "partnerId": "17546",
        "result": "Loss",
        "score": "24-22, 21-16",
        "matchLength": "0:35"
      },
      {
        "opponents": {
          "opponentA": "Alejandro Huerta",
          "opponentAId": "15404",
          "opponentB": "Cesar Menendez",
          "opponentBId": "10401",
          "opponentNationality": "Spain",
          "opponentNationalityCode": ""
        },
        "_id": "602c563ba7bbbbac8807c3ff",
        "tournament": "Qinzhou",
        "tournamentId": "3731",
        "season": 2020,
        "round": "Pool Play 2nd Round",
        "partner": "Nuttanon Inkiew",
        "partnerId": "17546",
        "result": "Loss",
        "score": "21-16, 21-14",
        "matchLength": "0:29"
      }
    ],
    "createdAt": "2021-02-16T23:23:06.407Z",
    "updatedAt": "2021-02-16T23:33:15.435Z",
    "__v": 0
  },
  {
  "_id": "602c53dcc004f7608c294fd3",
  "name": "Phoebe Bell",
  "firstName": "Phoebe",
  "lastName": "Bell",
  "gender": "W",
  "nationality": "Australia",
  "playerId": "14447",
  "tournaments": [
    {
      "_id": "602c53dcc004f7608c294fd4",
      "tournamentName": "Siem Reap",
      "tournamentCountry": "Cambodia",
      "tournamentId": "3746",
      "season": 2020,
      "finish": 17,
      "seed": "11",
      "partnerName": "Brittany Kendall",
      "partnerFirstName": "Brittany",
      "partnerLastName": "Kendall",
      "partnerBVId": "15386"
    },
    {
      "_id": "602c543db69be7d2d842f020",
      "tournamentName": "Sydney",
      "tournamentCountry": "Australia",
      "tournamentId": "3635",
      "season": 2019,
      "finish": 25,
      "seed": "21",
      "partnerName": "Jessyka Ngauamo",
      "partnerFirstName": "Jessyka",
      "partnerLastName": "Ngauamo",
      "partnerBVId": "13714"
    },
    {
      "_id": "602c5453b69be7d2d842f448",
      "tournamentName": "Kuala Lumpur",
      "tournamentCountry": "Malaysia",
      "tournamentId": "3596",
      "season": 2019,
      "finish": 33,
      "seed": "Q6",
      "partnerName": "Jessyka Ngauamo",
      "partnerFirstName": "Jessyka",
      "partnerLastName": "Ngauamo",
      "partnerBVId": "13714"
    },
    {
      "_id": "602c5462b69be7d2d842f6e0",
      "tournamentName": "Jinjiang",
      "tournamentCountry": "China",
      "tournamentId": "3643",
      "season": 2019,
      "finish": 33,
      "seed": "Q8",
      "partnerName": "Jessyka Ngauamo",
      "partnerFirstName": "Jessyka",
      "partnerLastName": "Ngauamo",
      "partnerBVId": "13714"
    },
    {
      "_id": "602c546cb69be7d2d842f86c",
      "tournamentName": "Nantong",
      "tournamentCountry": "China",
      "tournamentId": "3639",
      "season": 2019,
      "finish": 5,
      "seed": "2",
      "partnerName": "Jessyka Ngauamo",
      "partnerFirstName": "Jessyka",
      "partnerLastName": "Ngauamo",
      "partnerBVId": "13714"
    },
    {
      "_id": "602c546db69be7d2d842f8bf",
      "tournamentName": "Nanjing",
      "tournamentCountry": "China",
      "tournamentId": "3638",
      "season": 2019,
      "finish": 5,
      "seed": "2",
      "partnerName": "Jessyka Ngauamo",
      "partnerFirstName": "Jessyka",
      "partnerLastName": "Ngauamo",
      "partnerBVId": "13714"
    },
    {
      "_id": "602c5484b69be7d2d842fd1d",
      "tournamentName": "Gstaad",
      "tournamentCountry": "Switzerland",
      "tournamentId": "3618",
      "season": 2019,
      "finish": 41,
      "seed": "Q16",
      "partnerName": "Jessyka Ngauamo",
      "partnerFirstName": "Jessyka",
      "partnerLastName": "Ngauamo",
      "partnerBVId": "13714"
    },
    {
      "_id": "602c5492b69be7d2d842ffc1",
      "tournamentName": "Tokyo",
      "tournamentCountry": "Japan",
      "tournamentId": "3626",
      "season": 2019,
      "finish": 25,
      "seed": "Q9",
      "partnerName": "Jessyka Ngauamo",
      "partnerFirstName": "Jessyka",
      "partnerLastName": "Ngauamo",
      "partnerBVId": "13714"
    }
  ],
  "matches": [
    {
      "opponents": {
        "opponentA": "Mariota Angelopoulou",
        "opponentAId": "10644",
        "opponentB": "Daria Gusarova",
        "opponentBId": "17898",
        "opponentNationality": "Cyprus",
        "opponentNationalityCode": ""
      },
      "_id": "602c563aa7bbbbac8807b9ea",
      "tournament": "Siem Reap",
      "tournamentId": "3746",
      "season": 2020,
      "round": "Pool Play 1st Round",
      "partner": "Brittany Kendall",
      "partnerId": "15386",
      "result": "Loss",
      "score": "21-18, 21-18",
      "matchLength": "0:38"
    },
    {
      "opponents": {
        "opponentA": "Kimberly Hildreth",
        "opponentAId": "16015",
        "opponentB": "Sarah Schermerhorn",
        "opponentBId": "16898",
        "opponentNationality": "United States",
        "opponentNationalityCode": ""
      },
      "_id": "602c563aa7bbbbac8807b9f0",
      "tournament": "Siem Reap",
      "tournamentId": "3746",
      "season": 2020,
      "round": "Pool Play 2nd Round",
      "partner": "Brittany Kendall",
      "partnerId": "15386",
      "result": "Win",
      "score": "21-14, 21-16",
      "matchLength": "0:35"
    }
  ],
  "createdAt": "2021-02-16T23:23:08.127Z",
  "updatedAt": "2021-02-16T23:33:14.007Z",
  "__v": 0
}, 
  {
    "_id": "602c53e0c004f7608c295129",
    "name": "Bruno Oscar Schmidt",
    "firstName": "Bruno",
    "lastName": "Oscar Schmidt",
    "gender": "M",
    "nationality": "Brazil",
    "playerId": "8539",
    "tournaments": [
      {
        "_id": "602c53e0c004f7608c29512a",
        "tournamentName": "Doha",
        "tournamentCountry": "Qatar",
        "tournamentId": "3754",
        "season": 2020,
        "finish": 4,
        "seed": "6",
        "partnerName": "Evandro Goncalves",
        "partnerFirstName": "Evandro",
        "partnerLastName": "Goncalves",
        "partnerBVId": "11854"
      },
      {
        "_id": "602c5423b69be7d2d842eaea",
        "tournamentName": "Yangzhou",
        "tournamentCountry": "China",
        "tournamentId": "3447",
        "season": 2019,
        "finish": 9,
        "seed": "2",
        "partnerName": "Pedro Solberg",
        "partnerFirstName": "Pedro",
        "partnerLastName": "Solberg",
        "partnerBVId": "6767"
      },
      {
        "_id": "602c542bb69be7d2d842ec78",
        "tournamentName": "Las Vegas",
        "tournamentCountry": "United States",
        "tournamentId": "3557",
        "season": 2019,
        "finish": 9,
        "seed": "11",
        "partnerName": "Pedro Solberg",
        "partnerFirstName": "Pedro",
        "partnerLastName": "Solberg",
        "partnerBVId": "6767"
      },
      {
        "_id": "602c5432b69be7d2d842edaf",
        "tournamentName": "The Hague",
        "tournamentCountry": "Netherlands",
        "tournamentId": "3572",
        "season": 2019,
        "finish": 5,
        "seed": "7",
        "partnerName": "Pedro Solberg",
        "partnerFirstName": "Pedro",
        "partnerLastName": "Solberg",
        "partnerBVId": "6767"
      },
      {
        "_id": "602c5440b69be7d2d842f0bf",
        "tournamentName": "Doha",
        "tournamentCountry": "Qatar",
        "tournamentId": "3582",
        "season": 2019,
        "finish": 17,
        "seed": "9",
        "partnerName": "Evandro Goncalves",
        "partnerFirstName": "Evandro",
        "partnerLastName": "Goncalves",
        "partnerBVId": "11854"
      },
      {
        "_id": "602c544fb69be7d2d842f335",
        "tournamentName": "Xiamen",
        "tournamentCountry": "China",
        "tournamentId": "3591",
        "season": 2019,
        "finish": 17,
        "seed": "13",
        "partnerName": "Evandro Goncalves",
        "partnerFirstName": "Evandro",
        "partnerLastName": "Goncalves",
        "partnerBVId": "11854"
      },
      {
        "_id": "602c545ab69be7d2d842f579",
        "tournamentName": "Itapema",
        "tournamentCountry": "Brazil",
        "tournamentId": "3600",
        "season": 2019,
        "finish": 9,
        "seed": "11",
        "partnerName": "Evandro Goncalves",
        "partnerFirstName": "Evandro",
        "partnerLastName": "Goncalves",
        "partnerBVId": "11854"
      },
      {
        "_id": "602c5460b69be7d2d842f645",
        "tournamentName": "Jinjiang",
        "tournamentCountry": "China",
        "tournamentId": "3642",
        "season": 2019,
        "finish": 2,
        "seed": "10",
        "partnerName": "Evandro Goncalves",
        "partnerFirstName": "Evandro",
        "partnerLastName": "Goncalves",
        "partnerBVId": "11854"
      },
      {
        "_id": "602c5468b69be7d2d842f781",
        "tournamentName": "Ostrava",
        "tournamentCountry": "Czech Republic",
        "tournamentId": "3604",
        "season": 2019,
        "finish": 5,
        "seed": "10",
        "partnerName": "Evandro Goncalves",
        "partnerFirstName": "Evandro",
        "partnerLastName": "Goncalves",
        "partnerBVId": "11854"
      },
      {
        "_id": "602c5472b69be7d2d842f97f",
        "tournamentName": "Warsaw",
        "tournamentCountry": "Poland",
        "tournamentId": "3609",
        "season": 2019,
        "finish": 1,
        "seed": "11",
        "partnerName": "Evandro Goncalves",
        "partnerFirstName": "Evandro",
        "partnerLastName": "Goncalves",
        "partnerBVId": "11854"
      },
      {
        "_id": "602c547ab69be7d2d842fb11",
        "tournamentName": "Hamburg",
        "tournamentCountry": "Germany",
        "tournamentId": "3613",
        "season": 2019,
        "finish": 17,
        "seed": "16",
        "partnerName": "Evandro Goncalves",
        "partnerFirstName": "Evandro",
        "partnerLastName": "Goncalves",
        "partnerBVId": "11854"
      },
      {
        "_id": "602c5482b69be7d2d842fc5a",
        "tournamentName": "Gstaad",
        "tournamentCountry": "Switzerland",
        "tournamentId": "3617",
        "season": 2019,
        "finish": 3,
        "seed": "6",
        "partnerName": "Evandro Goncalves",
        "partnerFirstName": "Evandro",
        "partnerLastName": "Goncalves",
        "partnerBVId": "11854"
      },
      {
        "_id": "602c548bb69be7d2d842fe1e",
        "tournamentName": "Espinho",
        "tournamentCountry": "Portugal",
        "tournamentId": "3620",
        "season": 2019,
        "finish": 5,
        "seed": "1",
        "partnerName": "Evandro Goncalves",
        "partnerFirstName": "Evandro",
        "partnerLastName": "Goncalves",
        "partnerBVId": "11854"
      },
      {
        "_id": "602c5490b69be7d2d842ff3f",
        "tournamentName": "Tokyo",
        "tournamentCountry": "Japan",
        "tournamentId": "3625",
        "season": 2019,
        "finish": 5,
        "seed": "2",
        "partnerName": "Evandro Goncalves",
        "partnerFirstName": "Evandro",
        "partnerLastName": "Goncalves",
        "partnerBVId": "11854"
      },
      {
        "_id": "602c5496b69be7d2d843001c",
        "tournamentName": "Vienna",
        "tournamentCountry": "Austria",
        "tournamentId": "3627",
        "season": 2019,
        "finish": 9,
        "seed": "3",
        "partnerName": "Evandro Goncalves",
        "partnerFirstName": "Evandro",
        "partnerLastName": "Goncalves",
        "partnerBVId": "11854"
      },
      {
        "_id": "602c54a8b69be7d2d84302de",
        "tournamentName": "Moscow",
        "tournamentCountry": "Russia",
        "tournamentId": "3629",
        "season": 2019,
        "finish": 5,
        "seed": "3",
        "partnerName": "Evandro Goncalves",
        "partnerFirstName": "Evandro",
        "partnerLastName": "Goncalves",
        "partnerBVId": "11854"
      },
      {
        "_id": "602c54bab69be7d2d8430584",
        "tournamentName": "Rome",
        "tournamentCountry": "Italy",
        "tournamentId": "3640",
        "season": 2019,
        "finish": 5,
        "seed": "10",
        "partnerName": "Evandro Goncalves",
        "partnerFirstName": "Evandro",
        "partnerLastName": "Goncalves",
        "partnerBVId": "11854"
      }
    ],
    "matches": [
      {
        "opponents": {
          "opponentA": "Dries Koekelkoren",
          "opponentAId": "11600",
          "opponentB": "Tom van Walle",
          "opponentBId": "11601",
          "opponentNationality": "Belgium",
          "opponentNationalityCode": ""
        },
        "_id": "602c563aa7bbbbac8807bc69",
        "tournament": "Doha",
        "tournamentId": "3754",
        "season": 2020,
        "round": "Pool Play 1st Round",
        "partner": "Evandro Goncalves",
        "partnerId": "11854",
        "result": "Win",
        "score": "12-21, 21-14, 15-9",
        "matchLength": "0:45"
      },
      {
        "opponents": {
          "opponentA": "Billy Allen",
          "opponentAId": "6042",
          "opponentB": "Stafford Slick",
          "opponentBId": "10939",
          "opponentNationality": "United States",
          "opponentNationalityCode": ""
        },
        "_id": "602c563aa7bbbbac8807bc71",
        "tournament": "Doha",
        "tournamentId": "3754",
        "season": 2020,
        "round": "Pool Play 2nd Round",
        "partner": "Evandro Goncalves",
        "partnerId": "11854",
        "result": "Win",
        "score": "21-15, 21-17",
        "matchLength": "0:37"
      },
      {
        "opponents": {
          "opponentA": "Esteban Grimalt",
          "opponentAId": "12583",
          "opponentB": "Marco Grimalt",
          "opponentBId": "12656",
          "opponentNationality": "Chile",
          "opponentNationalityCode": ""
        },
        "_id": "602c563aa7bbbbac8807bccd",
        "tournament": "Doha",
        "tournamentId": "3754",
        "season": 2020,
        "round": " 9th Place Match",
        "partner": "Evandro Goncalves",
        "partnerId": "11854",
        "result": "Win",
        "score": "26-24, 21-17",
        "matchLength": "0:45"
      },
      {
        "opponents": {
          "opponentA": "Phil Dalhausser",
          "opponentAId": "5214",
          "opponentB": "Nick Lucena",
          "opponentBId": "1931",
          "opponentNationality": "United States",
          "opponentNationalityCode": ""
        },
        "_id": "602c563aa7bbbbac8807bce1",
        "tournament": "Doha",
        "tournamentId": "3754",
        "season": 2020,
        "round": " 5th Place Match",
        "partner": "Evandro Goncalves",
        "partnerId": "11854",
        "result": "Win",
        "score": "21-10, 21-12",
        "matchLength": "0:31"
      },
      {
        "opponents": {
          "opponentA": "Josue Gaxiola",
          "opponentAId": "15325",
          "opponentB": "Jose Rubio",
          "opponentBId": "15326",
          "opponentNationality": "Mexico",
          "opponentNationalityCode": ""
        },
        "_id": "602c563aa7bbbbac8807bcef",
        "tournament": "Doha",
        "tournamentId": "3754",
        "season": 2020,
        "round": "Semifinals ",
        "partner": "Evandro Goncalves",
        "partnerId": "11854",
        "result": "Loss",
        "score": "22-20, 22-20",
        "matchLength": "0:39"
      },
      {
        "opponents": {
          "opponentA": "Daniele Lupo",
          "opponentAId": "9422",
          "opponentB": "Paolo Nicolai",
          "opponentBId": "9059",
          "opponentNationality": "Italy",
          "opponentNationalityCode": ""
        },
        "_id": "602c563aa7bbbbac8807bcf3",
        "tournament": "Doha",
        "tournamentId": "3754",
        "season": 2020,
        "round": "Bronze Medal Match ",
        "partner": "Evandro Goncalves",
        "partnerId": "11854",
        "result": "Loss",
        "score": "21-19, 21-17",
        "matchLength": "0:34"
      }
    ],
    "createdAt": "2021-02-16T23:23:12.866Z",
    "updatedAt": "2021-02-16T23:33:14.477Z",
    "__v": 0
  }
]

export default players